theme: minima
author: Cathy Kim
title: Data Science
description: Data Science pipeline using credit card fraud detection dataset

defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
  
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
