title: Statistical Modeling Pipeline
logo: /assets/img/logo.png
description: Data Science Pipeline using Credit Card Fraud Detection Dataset
remote_theme: sighingnow/jekyll-gitbook
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

page_width: 800px


