theme: jekyll-theme-minimal
title: Data Science
description: Data Science pipeline using credit card fraud detection dataset

defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
