title: Statistical Modeling Pipeline
logo: /assets/img/logo.png
description: Data Science Pipeline using Credit Card Fraud Detection Dataset
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

page_width: 800px


